name = "Corda_Relay2"
port="9082"
host="localhost"
hostname="localhost"
db_path="db/Corda_Relay2/requests"
# This will be replaced by the task queue.
remote_db_path="db/Corda_Relay2/remote_request"

[networks]
[networks.Corda_Network2]
network="Corda"
[networks.Dummy_Network]
network="Dummy"

[relays]
[relays.Fabric_Relay]
hostname="localhost"
port="9080"
[relays.Fabric_Relay2]
hostname="localhost"
port="9083"
[relays.Dummy_relay]
hostname="localhost"
port="9085"
[relays.Corda_Relay]
hostname="localhost"
port="9081"

[drivers]
[drivers.Corda]
hostname="localhost"
port="9098"
[drivers.Dummy]
hostname="localhost"
port="9095"
