[relays.relay-network1]
hostname="relay-network1"
port="9080"

[relays.relay-network2]
hostname="relay-network2"
port="9083"

[relays.relay-corda]
hostname="relay-corda"
port="9081"

[relays.relay-corda2]
hostname="relay-corda2"
port="9082"

